dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0

compiler:
  solc:
    version: 0.8.0
    optimizer:
      enabled: true
      runs: 200

networks:
  default: development
  development:
    host: http://127.0.0.1
    port: 8546
    gas_limit: 6721975
    gas_price: 20000000000